# FlowCoro

## 

# 
set(FLOWCORO_MIN_GCC_VERSION "10.0")
set(FLOWCORO_MIN_CLANG_VERSION "12.0")
set(FLOWCORO_MIN_MSVC_VERSION "19.29")

# 
set(FLOWCORO_SUPPORTED_PLATFORMS "Linux;Windows;macOS")

# 
set(FLOWCORO_ENABLE_LOGGING_DEFAULT ON)
set(FLOWCORO_ENABLE_NETWORKING_DEFAULT ON)
set(FLOWCORO_ENABLE_MEMORY_POOLS_DEFAULT ON)

## 

# 
set(FLOWCORO_DEFAULT_THREAD_COUNT 0) # 0 = hardware_concurrency

# 
set(FLOWCORO_DEFAULT_LOG_BUFFER_SIZE 4096)
set(FLOWCORO_DEFAULT_RING_BUFFER_SIZE 1024)
set(FLOWCORO_DEFAULT_MEMORY_POOL_CHUNK_SIZE 64)

# 
set(FLOWCORO_CACHE_LINE_SIZE 64)
set(FLOWCORO_PAGE_SIZE 4096)
