# FlowCoro项目配置文件

## 构建配置

# 编译器要求
set(FLOWCORO_MIN_GCC_VERSION "10.0")
set(FLOWCORO_MIN_CLANG_VERSION "12.0")
set(FLOWCORO_MIN_MSVC_VERSION "19.29")

# 平台支持
set(FLOWCORO_SUPPORTED_PLATFORMS "Linux;Windows;macOS")

# 特性开关
set(FLOWCORO_ENABLE_LOGGING_DEFAULT ON)
set(FLOWCORO_ENABLE_NETWORKING_DEFAULT ON)
set(FLOWCORO_ENABLE_MEMORY_POOLS_DEFAULT ON)

## 性能配置

# 默认线程池大小
set(FLOWCORO_DEFAULT_THREAD_COUNT 0)  # 0 = hardware_concurrency

# 缓冲区大小配置
set(FLOWCORO_DEFAULT_LOG_BUFFER_SIZE 4096)
set(FLOWCORO_DEFAULT_RING_BUFFER_SIZE 1024)
set(FLOWCORO_DEFAULT_MEMORY_POOL_CHUNK_SIZE 64)

# 内存对齐配置
set(FLOWCORO_CACHE_LINE_SIZE 64)
set(FLOWCORO_PAGE_SIZE 4096)
